name: Flask CICD
 
# 觸發條件
on: [push]
 
# 執行一項或多項任務
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.7, 3.8, 3.9 ]
    runs-on: ${{ matrix.os }}
    steps:
    # step1: checkout code
    - name: Checkout Code
      uses: actions/checkout@v3
    # step2: setup python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # step3: install dependencies
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r ./requirements.txt
    # step4: run test
    - name: Run Tests
      run: |
        python3 test_app.py
